### ISSUE TITLE
Network error on startup

### ISSUE THREAD

**Issue by nielsdg** [ZeusWPI/hydra-iOS#2]
It seems to be a problem with the resto menu, since the info is outdated.

![image](https://cloud.githubusercontent.com/assets/1382976/13427652/b24d543e-dfb5-11e5-93bb-ca1954365fc8.png)

**Comment by feliciaan** [comment]
It's because the next week is not parsed.

**Comment by feliciaan** [comment]
@nielsdg next week is december: https://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week50 :(

**Comment by nielsdg** [comment]
It seems that there is no week 10. However, why are we giving an URL to week 50?

**Comment by feliciaan** [comment]
The link beneath the date of next is week 50 :(

**Comment by nielsdg** [comment]
Ah, I see. Then maybe use the URL mentioned in one of the other comments (with rss2json at the end) or [this one](https://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/)?

**Comment by feliciaan** [comment]
I'm gonna close the issue here, and create a one in the main hydra repo.
